apiVersion: "v1"
kind: Pod
metadata:
  name: mynginx-pod
  labels:
    app: demo
    env: test
spec:
  containers:
    - name: nginx
      image: nginx:1.9.0
      ports:
        - name: http
          containerPort: 80
          protocol: TCP
