apiVersion: "apps/v1beta1"
kind: Deployment
metadata:
  name: webapp
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: webapp-demo
        env: test
    spec:
      containers:
        - name: uodashboard
          image: mohitsharma44/uodashboard-container:dev
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 30000
              protocol: TCP
