apiVersion: v1
kind: Service
metadata:
    name: webapp-svc
spec:
  type: NodePort
  selector:
    app: webapp-demo
    env: test
  ports:
  - name: http
    protocol: "TCP"
    port: 8888
    nodePort: 30000
